//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSH_HOTELSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotels()
        {
            this.images = new HashSet<images>();
            this.reviews = new HashSet<reviews>();
        }
    
        public int idhotel { get; set; }
        public string nomhotel { get; set; }
        public string ville { get; set; }
        public Nullable<int> nbetoile { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> prix { get; set; }
        public string descr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<images> images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reviews> reviews { get; set; }
    }
}
