//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSH_HOTELSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hmsEntities : DbContext
    {
        public hmsEntities()
            : base("name=hmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hotels> hotels { get; set; }
        public virtual DbSet<images> images { get; set; }
        public virtual DbSet<reviews> reviews { get; set; }
        public virtual DbSet<uroles> uroles { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
