//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSH_HOTELSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int idrev { get; set; }
        public string titlerev { get; set; }
        public string descr { get; set; }
        public Nullable<int> idhotel { get; set; }
        public Nullable<int> iduser { get; set; }
        public Nullable<int> score { get; set; }
    
        public virtual hotels hotels { get; set; }
        public virtual users users { get; set; }
    }
}
